name: (Manually run) Create LS Package Index
on:
  workflow_dispatch:

jobs:
  run-ballerina:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ballerina-platform/setup-ballerina@v1
        name: Install Ballerina
        with:
          version: 2201.10.0
      - run: bal version
      - run: bal run
